version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka1
    ports:
      - "9092:9092"      # host access (optional)-
      - "29092:29092"    # internal container access
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      DB_URL: mongodb://mongo:27017/mern
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - mongo
      - kafka
    networks:
      - app-network

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      DB_URL: mongodb://mongo:27017/mern
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - mongo
      - kafka
    networks:
      - app-network

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      DB_URL: mongodb://mongo:27017/mern
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - mongo
      - kafka
    networks:
      - app-network

  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    environment:
      DB_URL: mongodb://mongo:27017/mern
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - mongo
      - kafka
    networks:
      - app-network

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"  # host access
    depends_on:
      - user-service
      - product-service
      - order-service
      - wallet-service
    networks:
      - app-network
